### ISSUE TITLE
Security focused group?

### ISSUE THREAD

**Issue by mikecali** [open-gitops/project#32]
GitOps Security Considerations
Securing GitOps is very important especially in an automated environment. If we don’t take security into consideration upfront we are opening Pandora’s box. A multitude of things can go wrong if security is an afterthought.

1. Security must be part of every design and should be continuous.
2. GitOps RBAC - controller?
3. Embed code validation steps 
4. Git Repository Governance.
5. Level of access to different personalities.
6. Imposing Git best practices all the time.
7. Systems/Environments access control.
8. Who can access different tooling.
9. Making sure access are logged.

This is just a thought that might need consideration for this project.

**Comment by lloydchang** [comment]
Hi, @mikecali,

There are existing groups: [CNCF Security Technical Advisory Group](https://github.com/cncf/tag-security) and [Kubernetes Security Special Interest Group](https://github.com/kubernetes/community/tree/master/sig-security).

Information Security is driven by [the principles of Availability, Integrity, Confidentiality (AIC) triad, and Non-repudiation](https://en.wikipedia.org/wiki/Information_security).  Generally-speaking, [ISO/IEC 27001 is an international standard](https://en.wikipedia.org/wiki/ISO/IEC_27001) on how to manage information security.

Being prescriptive about "must" and "all the time" may not be practical because situations and circumstances would influence risk assessment and [risk appetite](https://en.wikipedia.org/wiki/Risk_appetite).

Since Git is distributed by design, it would be impractical to enforce governance in a centralized manner.  Perhaps you mean "GitHub" or "GitLab" instead of Git in "Git Repository Governance"? 

Security is a broad topic.  A YouTube search for videos for the words "GitOps" and "Security" returns:
• [Secure Your GitOps - How to Implement a Robust Security Strategy (2021)](https://www.youtube.com/watch?v=smjV-Gd8p6M)
• [GitOps & Runtime Security Your Cookies Need a New Recipe (2021)](https://www.youtube.com/watch?v=oR8rlaxmiRs)
• [Securing GitOps (2021)](https://www.youtube.com/watch?v=OmDdKVMF9jw)
• [Security and GitOps (2020)](https://www.youtube.com/watch?v=mneDm2ebl-g)
• [Security Benefits from Adopting GitOps (2020)](https://www.youtube.com/watch?v=onwHlCDN5lU)
• [Continuous Security – Building Security Into Your Pipelines (2020)](https://www.youtube.com/watch?v=A-RqhHTl1ok)
• [Security, Compliance, & Governance for Your Enterprise Use Case (2020)](https://www.youtube.com/watch?v=zYnnThcFQhI)
and there are probably more videos...

**Comment by lloydchang** [comment]
@mikecali On the off chance that you have time availability to contribute to the topic of security within this project, then this is just a suggestion:

* Maybe you could help proofread [`SECURITY.md`](https://github.com/open-gitops/.github/blob/main/SECURITY.md)?

Besides @scottrigby, @todaywasawesome, @murillodigital, I don't know how many other people have read that [`SECURITY.md`](https://github.com/open-gitops/.github/blob/main/SECURITY.md) yet.

Thank you.

**Comment by mikecali** [comment]
Thanks, @lloydchang - The reason I suggested this is because we always see in the real-life implementation that "security considerations are left behind".

I have seen some of those videos and they are indeed good. My thinking is providing guidance upfront for security is needed.

**Comment by lloydchang** [comment]
@mikecali To advance this beyond _just a thought_, I believe you would need to formalize it as a topic in https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.pgfeyjjsd1o8

**Comment by roberthstrand** [comment]
I agree that security is something that we should try to cover. We haven't really been talking about security so far, but it's a topic that can get very advanced and we can help by creating some guidance on this topic. It doesn't have to be very big effort either, and as long as we have clear goals on what we want to achieve then I'm all for helping to facilitate it. I'll bring it up in the meeting today.

**Comment by lloydchang** [comment]
@mikecali @roberthstrand Thank you.

If you would like a concrete example from implementations:

Premise: Webhooks compromise our GitOps [security posture](https://csrc.nist.gov/glossary/term/security_posture).

Why # 1: [Public exposure on Internet:](https://fluxcd.io/docs/guides/webhook-receivers/#expose-the-webhook-receiver)
> [In order to receive Git push or Helm chart upload events, you'll have to expose the webhook receiver endpoint outside of your Kubernetes cluster on a public address.](https://fluxcd.io/docs/guides/webhook-receivers/#expose-the-webhook-receiver)

Why # 2: [When webhooks push intentionally at high rates, this situation introduces security risks of incoming events needing to be rate limited at the ingress (i.e. ingress-nginx, or load balancer (LB), or web application firewall (WAF), etc.) to prevent denial of service (DOS) attacks.](https://github.com/fluxcd/website/pull/612#issuecomment-955841005)

Why # 3: There is a lack of validation in some webhook receivers

For example: Flux CD v2's webhook receivers with details in:
1. [Update docs on Generic/HMAC receiver payload fluxcd/notification-controller#256](https://github.com/fluxcd/notification-controller/issues/256)
2. [docs(webhook-receivers.md): validation fluxcd/website#621](https://github.com/fluxcd/website/pull/621)
3. [docs(webhook-receivers.md): responsiveness fluxcd/website#612](https://github.com/fluxcd/website/pull/612)

While [your guidance with clear goals](https://github.com/open-gitops/project/issues/32#issuecomment-964888948) might not be as nuanced as webhook receivers exposed publicly on the Internet, I would say that simple is hard.

As our [Panel Discussion: OpenGitOps and the GitOps Working Group](https://www.youtube.com/watch?v=p0ntvMyqmr4&t=685s) said, "[simple is really, really, hard.](https://www.youtube.com/watch?v=p0ntvMyqmr4&t=685s)"

**Comment by todaywasawesome** [comment]
I agree 💯  @mikecali 

Would you be interested in starting a greenpaper/whitepaper on this topic?

**Comment by mikecali** [comment]
I will be happy to contribute to creating a whitepaper.
Let me start putting together some ideas on the content and will share them back here.

@todaywasawesome @lloydchang @roberthstrand - thanks for your support.

**Comment by roberthstrand** [comment]
@mikecali - Since these documents are going to live in the documents repository, I have suggested to enable discussions to make work on specific white/green papers or pattern descriptions easier. Issue can be found [here](https://github.com/open-gitops/documents/issues/44).

At that point brainstorming specific ideas would be easier, at least I hope so.

**Comment by yebyen** [comment]
I would be interested to contribute further to the discussion @lloydchang about how webhooks of different forms can have compromised the security posture, and what promises the different mitigations that are possible can offer to repair or obviate them. re: https://github.com/open-gitops/project/issues/32#issuecomment-964950127

I consider from my perspective that the addition of a new timing source which does not carry any specific utilized information, other than the timing for when a specific Source reconciliation should be attempted early, does not compromise much. But in the lens of Simple Is Hard, I can see how those specific caveats might introduce a lot of complexity that includes some promises, and certain conditions which we might not want to entertain, so I consider too this is a good topic with a lot of specific nuance in it.

**Comment by lloydchang** [comment]
This depends on how @mikecali and @roberthstrand want to facilitate @yebyen's request https://github.com/open-gitops/project/issues/32#issuecomment-965799100

@yebyen My suggestion is that you consider _transforming your perspective_ from focusing on a new timing source to a broader focus of [a threat model](https://en.wikipedia.org/wiki/Threat_model).

Simple is hard, and security issues can be nuanced.

**Scenario:** For the sole purpose of facilitating webhooks' [public exposure on the Internet](https://fluxcd.io/docs/guides/webhook-receivers/#expose-the-webhook-receiver), your organization installs a web application firewall.  Accidentally, misconfiguration happens and increases [the attack surface](https://en.wikipedia.org/wiki/Attack_surface), and no one in your organization is aware of the security issue...

**Questions:**
1. If you [plead ignorance](https://www.merriam-webster.com/dictionary/plead%20ignorance), then did any of this happen?
2. ["If a tree falls in a forest and no one is around to hear it, does it make a sound?"](https://en.wikipedia.org/wiki/If_a_tree_falls_in_a_forest)
3. What would you do before, during and after a [data breach](https://en.wikipedia.org/wiki/Data_breach)?

Here is an example about misconfiguration from https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/
> [What We Can Learn from the Capital One Hack](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> [On Monday, a former Amazon employee was arrested and charged with stealing more than 100 million consumer applications for credit from Capital One. Since then, many have speculated the breach was perhaps the result of a previously unknown “zero-day” flaw, or an “insider” attack in which the accused took advantage of access surreptitiously obtained from her former employer. But new information indicates the methods she deployed have been well understood for years.](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> [[...]](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> [According to a source with direct knowledge of the breach investigation, the problem stemmed in part from a misconfigured open-source Web Application Firewall (WAF) that Capital One was using as part of its operations hosted in the cloud with Amazon Web Services (AWS).](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> [[...]](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> ["The intrusion was caused by a misconfiguration of a web application firewall and not the underlying infrastructure or the location of the infrastructure," the statement reads. "AWS is constantly delivering services and functionality to anticipate new threats at scale, offering more security capabilities and layers than customers can find anywhere else including within their own datacenters, and when broadly used, properly configured and monitored, offer unmatched security—and the track record for customers over 13+ years in securely using AWS provides unambiguous proof that these layers work."](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)
>
> [[...]](https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/)

**Comment by yebyen** [comment]
I view this as fear mongering, simply put the Flux webhook attack surface is very tight, but there can always be room for improvement. I'm interested in a benchmark that shows how even a generic webhook with no signature verification can be exploited in the Flux notification controller, I am skeptical that it can break at any threshold of load based on what happens.

I would be more skeptical of signed, verified webhooks, since checking the signature and validating payload invokes more code paths than simply triggering a reconcile of Flux's GitRepository resource, which is what happens when Receiver is properly implemented. If this works how I expect, then Flux should only pull the head commit from the Git Repository branch, a lightweight operation which can abort as soon as two pre-computed SHAs are compared (the cached HEAD and the remote) and seen not having changed at all, the operation should take practically no calculation or bandwidth at all. (Verifying a signature, on the other hand, depending on algorithms used could surely be susceptible to DDoS in cases where this approach would have not been.)

Not all implementations can be said to have been properly implemented, but neither can the software take responsibility for improper implementation that falls outside of its scope of control. (You can misconfigure a firewall and that doesn't make Flux's approach to webhooks any worse for design.)

If there is a security issue in Flux's notification controller, thenlet's expose it and offer steps to mitigate the issue. If there are no provably insecure paths then we can at least allay some concerns and perhaps put the issue to rest, with respect to Flux at least.

**Comment by lloydchang** [comment]
@yebyen wrote:
>  let's expose it

https://github.com/fluxcd/notification-controller/issues/256 reported an issue

> offer steps to mitigate the issue

https://github.com/fluxcd/website/pull/621 mitigates the reported issue

**Comment by lloydchang** [comment]
@yebyen Would you kindly review both https://github.com/fluxcd/notification-controller/issues/256 and https://github.com/fluxcd/website/pull/621 when your time permits?  Thank you.

**Comment by kingdonb** [comment]
fluxcd/notification-controller#256 reported a potential issue, I simply mean that would like to understand how it can be exploited. I mean let's have benchmarks that show, given resources (compute nodes of size X) an attacker who exploits the (signed, or unsigned/unverified) webhook can currently express the webhook in order to saturate cluster resources.

If there is a need for rate limiting here, then let's show the risk exposure and if possible impose the necessary rate limiting.

Simply adding a note that "here, a door can be configured as closed/locked, or it can be left open" is not adding any serious mitigation. Webhooks can be signed or unsigned, and their payloads can be validated or not. Either way, according to the design of Flux's notification controller, the payload is a nonce and can be disposed without processing. This seems objectively safe to me, but I don't have benchmarks to prove it.

 If this is an attack surface that can be exploited, let's show the impact of the exploit (with benchmarks.) Then we can approach to mitigate the impact, if it is detectable, but until data shows this is an exploitable entryway, we cannot turn it off. The performance impact of reconciling too often is "the devil we know." As the number of Reconciler resources grows, this has a very real impact that you can measure on control plane performance. In that sense, I mean to say that: the notification controller's Receiver feature allows us to mitigate the devil we know.

I believe @yebyen is merely suggesting, let's hear more about this devil we don't know, the attack vector of hitting the receive hook with unnecessarily high and abusive frequency. How fast exactly do you have to trigger it before you can detect any observable impact on performance? (And for documentation that closes the loop, it would be good to include further notes explaining how can one further mitigate this impact with a correctly configured WAF?)

**Comment by lloydchang** [comment]
I do not have the time availability to create a [threat model](https://en.wikipedia.org/wiki/Threat_model), followed by a benchmark with data.

For each implementation of GitOps, it may be cost prohibitive for the GitOps Working Group to create a [threat model](https://en.wikipedia.org/wiki/Threat_model), followed by a benchmark with data.

I was unaware of "the devil we know" regarding:
> As the number of Reconciler resources grows, this has a very real impact that you can measure on control plane performance.

Thank you @yebyen and @kingdonb

**Comment by lloydchang** [comment]
@mikecali @roberthstrand The 29 recommendations in https://fluxcd.io/FluxFinalReport-v1.1.pdf may be of interest to you as concrete examples based on an existing CNCF incubated project, Flux CD v2.

Thank you.

**Comment by yebyen** [comment]
Adding more reconcilers (GitRepository, Kustomization) is the mechanism by which we scale GitOps to work effectively with many apps (and even many tenants) inside a cluster. So to clarify what I mean, while the performance impact of adding many reconcilers is real, the performance impact of adding more manifests to a single reconciler until scale is reached, is also real, and creates a single point of failure, which is worse.

It can be in scope for individual GitOps projects to deliver these benchmarks, I agree it wouldn't be in scope for OpenGitOps to do it all; but perhaps it could be in scope for the project to provide a prescriptive framework for such benchmarks. I think that the upstream-downstream model of Kustomization which subscribes to GitRepository to intake and apply changes will perform impressively, even under the threat model presented here, I just don't have benchmarks to prove it. (Nor are my clusters "at scale" for now at least.)

Either way I meant to point out that we don't have great benchmarks for this threat model, or for at-scale deployments at large. Users will want to know at what scale their control planes will start to feel overwhelmed (in or outside of any threat model we may have to add to the conversation about performance.)

The threat model of course has more to consider than only performance and DDoS resilience. There could be risk of compromises that are not even related to performance.

**Comment by lloydchang** [comment]
@mikecali @roberthstrand

For your consideration from https://www.pmi.org/learning/library/managing-challenges-triple-constraints-6884

[**Manager's challenges--managing constraints**: This paper introduces a new concept, the **“management constraint triangle,”** and evaluates how these management constraints can potentially affect projects.](https://www.pmi.org/learning/library/managing-challenges-triple-constraints-6884)

> [**Resources –**](https://www.pmi.org/learning/library/managing-challenges-triple-constraints-6884)
> [If we change the “system” used in the project, then “expense” under “Financials” might be impacted. Using the same example above, **if additional information security regulation and policy/compliance requirements were added to the project, then project expense would increase with the addition of information security expert to the project.**](https://www.pmi.org/learning/library/managing-challenges-triple-constraints-6884)

**Comment by roberthstrand** [comment]
I am closing this issue in favor of #128. If anyone wants to join forces and create content around GitOps security, please volunteer in that issue.
